name: "Moobile"

exports: "moobile.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools for mobile devices"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Vendor/iscroll/src/iscroll-lite.js"

  - "Source/Browser/Browser.Platform.js"
  - "Source/Core/Core.js"
  - "Source/Event/Event.Mobile.js"
  - "Source/Event/Event.Ready.js"
  - "Source/Event/Event.Click.js"
  - "Source/Request/Request.js"
  - "Source/Request/Request.ViewController.js"
  - "Source/UI/UI.Control.js"
  - "Source/UI/UI.Button.js"
  - "Source/UI/UI.ButtonStyle.js"
  - "Source/UI/UI.Element.js"
  - "Source/UI/UI.Bar.js"
  - "Source/UI/UI.BarStyle.js"
  - "Source/UI/UI.Bar.Navigation.js"
  - "Source/UI/UI.BarButton.js"
  - "Source/UI/UI.BarButtonStyle.js"
  - "Source/UI/UI.List.js"
  - "Source/UI/UI.ListItem.js"
  - "Source/View/View.js"
  - "Source/View/View.Scroll.js"
  - "Source/View/ViewStack.js"
  - "Source/View/ViewStack.Navigation.js"
  - "Source/View/ViewPanel.js"
  - "Source/ViewController/ViewController.js"
  - "Source/ViewController/ViewControllerStack.js"
  - "Source/ViewController/ViewControllerStack.Navigation.js"
  - "Source/ViewController/ViewControllerPanel.js"
  - "Source/ViewController/ViewControllerPanel.Split.js"
  - "Source/ViewControllerTransition/ViewControllerTransition.js"
  - "Source/ViewControllerTransition/ViewControllerTransition.Slide.js"
  - "Source/ViewControllerTransition/ViewControllerTransition.Cubic.js"
  - "Source/ViewControllerTransition/ViewControllerTransition.Fade.js"
  - "Source/Window/Window.js"
