name: "Moobile"

exports: "moobile.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools for mobile devices"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Vendor/iscroll/src/iscroll.js"

  - "Source/Browser/Browser.Platform.js"

  - "Source/Class/Class.Instantiate.js"

  - "Source/Types/String.js"
  - "Source/Types/Array.js"

  - "Source/Element/Element.js"

  - "Source/Event/Event.Mobile.js"
  - "Source/Event/Event.Ready.js"
  - "Source/Event/Event.Click.js"
  - "Source/Event/Event.CSS3.js"
  - "Source/Event/Event.Rotate.js"

  - "Source/Request/Request.js"
  - "Source/Request/Request.ViewElement.js"

  - "Source/Entity/Entity.js"

  - "Source/Control/Control.js"
  - "Source/Control/Button.js"
  - "Source/Control/ButtonGroup.js"
  - "Source/Control/Bar.js"
  - "Source/Control/BarItem.js"
  - "Source/Control/BarButton.js"
  - "Source/Control/BarButtonGroup.js"
  - "Source/Control/NavigationBar.js"
  - "Source/Control/NavigationBarItem.js"
  - "Source/Control/Slider.js"
  - "Source/Control/List.js"
  - "Source/Control/ListItem.js"
  - "Source/Control/ActivityIndicator.js"
  - "Source/Control/Image.js"
  - "Source/Control/Overlay.js"
  - "Source/Control/Alert.js"
  - "Source/Control/Text.js"

  - "Source/View/View.js"
  - "Source/View/ViewContent.js"
  - "Source/View/ScrollView.js"
  - "Source/View/ViewPanel.js"
  - "Source/View/ViewPanelContent.js"
  - "Source/View/ViewStack.js"
  - "Source/View/ViewStackContent.js"

  - "Source/Scroller/Scroller.js"
  - "Source/Scroller/Scroller.Engine.js"
  - "Source/Scroller/Scroller.Engine.IScroll.js"
  - "Source/Scroller/Scroller.Engine.Native.js"

  - "Source/ViewTransition/ViewTransition.js"
  - "Source/ViewTransition/ViewTransition.Slide.js"
  - "Source/ViewTransition/ViewTransition.Cover.js"
  - "Source/ViewTransition/ViewTransition.Cover.Box.js"
  - "Source/ViewTransition/ViewTransition.Cover.Page.js"
  - "Source/ViewTransition/ViewTransition.Cubic.js"
  - "Source/ViewTransition/ViewTransition.Fade.js"
  - "Source/ViewTransition/ViewTransition.Flip.js"
  - "Source/ViewTransition/ViewTransition.None.js"
  - "Source/ViewController/ViewController.js"

  - "Source/ViewController/ViewControllerStack.js"
  - "Source/ViewController/ViewControllerStack.Navigation.js"
  - "Source/ViewController/ViewControllerPanel.js"

  - "Source/Window/Window.js"
  - "Source/Window/WindowContent.js"
  - "Source/Window/WindowController.js"
