name: "Moobile"

exports: "moobile.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools for mobile devices"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Vendor/iscroll/src/iscroll.js"
  - "Source/Browser/Browser.Platform.js"
  - "Source/Class/Class.Instanciate.js"
  - "Source/Types/Object.Extras.js"
  - "Source/Types/String.Extras.js"
  - "Source/Types/Array.Extras.js"
  - "Source/Element/Element.Styles.js"
  - "Source/Element/Element.Ingest.js"
  - "Source/Element/Element.Properties.Name.js"
  - "Source/Element/Element.Properties.Role.js"
  - "Source/Element/Element.Properties.Options.js"
  - "Source/Event/Event.Mobile.js"
  - "Source/Event/Event.Ready.js"
  - "Source/Event/Event.Click.js"
  - "Source/Event/Event.CSS3.js"
  - "Source/Event/Event.ViewLoad.js"
  - "Source/Event/Event.ViewReady.js"
  - "Source/Request/Request.js"
  - "Source/Request/Request.View.js"
  - "Source/Control/Control.js"
  - "Source/Control/Button.js"
  - "Source/Control/ButtonStyle.js"
  - "Source/Control/ButtonGroup.js"
  - "Source/Control/ButtonGroupStyle.js"
  - "Source/Control/Bar.js"
  - "Source/Control/BarStyle.js"
  - "Source/Control/NavigationBar.js"
  - "Source/Control/NavigationItem.js"
  - "Source/Control/BarButton.js"
  - "Source/Control/BarButtonStyle.js"
  - "Source/Control/Slider.js"
  - "Source/Control/List.js"
  - "Source/Control/ListStyle.js"
  - "Source/Control/ListItem.js"
  - "Source/Control/ListItemStyle.js"
  - "Source/Control/ActivityIndicator.js"
  - "Source/Control/ActivityIndicatorStyle.js"
  - "Source/UI/Image.js"
  - "Source/UI/Label.js"
  - "Source/View/View.js"
  - "Source/View/View.Roles.js"
  - "Source/View/ScrollView.js"
  - "Source/View/ViewPanel.js"
  - "Source/View/ViewStack.js"
  - "Source/Scroller/Scroller.js"
  - "Source/ViewTransition/ViewTransition.js"
  - "Source/ViewTransition/ViewTransition.Slide.js"
  - "Source/ViewTransition/ViewTransition.Cover.js"
  - "Source/ViewTransition/ViewTransition.Cubic.js"
  - "Source/ViewTransition/ViewTransition.Fade.js"
  - "Source/ViewTransition/ViewTransition.Flip.js"
  - "Source/ViewTransition/ViewTransition.None.js"
  - "Source/ViewController/ViewController.js"
  - "Source/ViewController/ViewControllerStack.js"
  - "Source/ViewController/ViewControllerStack.Navigation.js"
  - "Source/ViewController/ViewControllerPanel.js"
  - "Source/Window/Window.js"
  - "Source/Window/WindowController.js"
